# syntax=docker/dockerfile:1

#use
FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app
ADD start.sh /
RUN chmod +x /start.sh
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:resolve

COPY src ./src



CMD ["/start.sh"]